
package domain;

import java.io.Serializable;
import java.sql.*;
import java.util.Objects;

public class Staff implements Serializable {
    private int id;
    private String position;
    private String status;
    private Date dateStart;
    private Date dateEnd;
    private WebUser webUser;

    public Staff() {
    }
    
    public Staff(String position, String status, Date dateStart, Date dateEnd, WebUser webUser) { // ID to be generated by database
        this.id = id;
        this.position = position;
        this.status = status;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.webUser = webUser;
    }

    public Staff(int id, String position, String status, Date dateStart, Date dateEnd, WebUser webUser) {
        this.id = id;
        this.position = position;
        this.status = status;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.webUser = webUser;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getDateStart() {
        return dateStart;
    }

    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    public Date getDateEnd() {
        return dateEnd;
    }

    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    public WebUser getWebUser() {
        return webUser;
    }

    public void setWebUser(WebUser webUser) {
        this.webUser = webUser;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Staff other = (Staff) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }   
    
}
